# Generated by Django 4.1 on 2022-09-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
    ]
